efficientdet_d0:
  - image_width: 512
  - image_height: 512

efficientdet_d1:
  - image_width: 640
  - image_height: 640

tf_efficientdet_d0:
  - image_width: 512
  - image_height: 512  

tf_efficientdet_d1:
  - image_width: 640
  - image_height: 640  

tf_efficientdet_d2:
  - image_width: 768
  - image_height: 768 

tf_efficientdet_d3:
  - image_width: 896
  - image_height: 896 

tf_efficientdet_d4:
  - image_width: 1024
  - image_height: 1024 

tf_efficientdet_d5:
  - image_width: 1280
  - image_height: 1280

tf_efficientdet_d6:
  - image_width: 1280
  - image_height: 1280

tf_efficientdet_d7:
  - image_width: 1536
  - image_height: 1536  

tf_efficientdet_d7x:
  - image_width: 1536
  - image_height: 1536

tf_efficientdet_lite0:
  - image_width: 320
  - image_height: 320